apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "translator.yaml"
  - "telegraf.yaml"

configMapGenerator:
  - name: seichi-timed-stats-telegraf-config
    files:
      - "telegraf-config/telegraf.conf"
