apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: seichi-timed-stats-server
    component: translator
  name: seichi-timed-stats-translator
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: seichi-timed-stats-server
      component: translator
  template:
    metadata:
      labels:
        app: seichi-timed-stats-server
        component: translator
    spec:
      containers:
        - resources:
            requests:
              # This component allocates about 200Mi when queried by a single client to look at 45k-players datasource
              memory: 350Mi
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: seichi-timed-stats-translator
          image: ghcr.io/giganticminecraft/seichi-timed-stats-translator:sha-f81c212
          name: seichi-timed-stats-translator
          ports:
            - containerPort: 80
              name: metrics
          startupProbe:
            tcpSocket:
              port: 80
            # 最大20秒待つ
            failureThreshold: 5
            periodSeconds: 4

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seichi-timed-stats-translator
data:
  # Override this
  GAME_DATA_SERVER_GRPC_ENDPOINT_URL: "https://example.com"
  RUST_LOG: "info"

---
apiVersion: v1
kind: Service
metadata:
  name: seichi-timed-stats-translator
spec:
  type: ClusterIP
  ports:
    - name: seichi-timed-stats-translator-web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: seichi-timed-stats-server
    component: translator
